### ISSUE TITLE
Tabs not hidden

### ISSUE THREAD

**Issue by aemonge** [alex-pl/full-fullscreen#1] opened 2015-12-16 13:28 UTC
Hi !!!

This extension is amazing, even tough it's crappy from iOs that you need an extra extension to keep things working as expected q=.

I'm having a issues with it, the address bar does hide on full screen. But the tab-bar doesn't. And also on mouse hover the address bar wont show up (but this last issues isn't such a big deal for me)

**Comment by alex-pl** [comment] 2015-12-17 14:08
Thank you for reporting this problem!

Apple changed the meaning of it’s full screen mode, so it’s not directly Mozillas fault. They try to apply Apple’s design rules which is basically a good thing. But I wonder why there is no about:config switch for that. Don't know, but for this we have Add-ons! ;)

> the address bar does hide on full screen. But the tab-bar doesn't

I'm not able to reproduce you behavior here. Can you tell me your OS X and Firefox version? You could also try to temporary disable other Add-ons.

> on mouse hover the address bar wont show up

Yup, thats how it should work for now. I'll change this behavior later when I have enough time.

**Comment by aemonge** [comment] 2015-12-18 14:02
Hi !!!

Sorry I should had disable my addons first before opening this. It's working as expected, but there's an incompatibility with [ toolbarpositionchanger: https://github.com/tumpio/toolbarpositionchanger ]. I though tabs where hidden using some kind of visibility toggle, and that it shouldn't be affected by it's position. 

Never the less I'll also provide you with my versions, if you think you can make the enhancement of being compatible with that other plugin (:

Firefox: 42
Mac: 10.10.5

thank you so very much for being so kind and pleasant (:
Cheers !!!

**Comment by alex-pl** [comment] 2016-08-19 22:28
I just had a look into this issue and tried to reproduce it with the following setup:
- Firefox 48.0.1
- Mac OS X 10.11.6
- Fullscreen+ 1.1 and 1.2.0
- Toolbar Position Changer 0.2.3

I tried several toolbar positions but wasn't able to reproduce the issue. 

(I tried to test it in Firefox Nightly as well, but it seems like Toolbar Position Changer is broken in the Nightly version.)

Maybe the issue had been indirectly solved by an update of Firefox or Toolbar Position Changer. As I'm not able to reproduce this, I'll close the issue know. If you are still able to reproduce this, feel free to reopen it and I'll have a look into it. Make sure to include an instruction where I should place my toolbars to be able to reproduce it :).

Thanks again and sorry for the long delay!

**Closed as completed by alex-pl** 2016-08-19 22:28 UTC
Labels: bug

**Comment by aemonge** [comment] 2016-08-22 13:27
Yes, it working for me as well. !!!
